In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/patel-mark/PitchPredict/refs/heads/main/football_stats_big5_expanded.csv')
df.head()

,ranker,team,comp,players_used,avg_age,possession,games,games_starts,minutes,minutes_90s,...,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,xg_per90,xg_assist_per90,xg_xg_assist_per90,npxg_per90,npxg_xg_assist_per90
0,1,Alavés,es La Liga,25,27.2,44.0,21,231,"1,890",21.0,...,1.19,0.57,1.76,0.95,1.52,1.10,0.61,1.71,0.88,1.48
1,2,Angers,fr Ligue 1,23,28.1,42.4,19,209,"1,710",19.0,...,1.05,0.68,1.74,0.89,1.58,1.18,0.82,2.01,1.02,1.84
2,3,Arsenal,eng Premier League,24,26.4,55.2,23,253,"2,070",23.0,...,1.83,1.39,3.22,1.74,3.13,1.64,1.23,2.87,1.57,2.80
3,4,Aston Villa,eng Premier League,24,27.6,49.5,23,253,"2,070",23.0,...,1.43,1.13,2.57,1.35,2.48,1.47,1.07,2.54,1.36,2.43
4,5,Atalanta,it Serie A,28,27.3,56.0,22,242,"1,980",22.0,...,2.14,1.55,3.68,2.00,3.55,1.67,1.23,2.91,1.53,2.77

In [3]:
df.columns

Index(['ranker', 'team', 'comp', 'players_used', 'avg_age', 'possession',
       'games', 'games_starts', 'minutes', 'minutes_90s', 'goals', 'assists',
       'goals_assists', 'goals_pens', 'pens_made', 'pens_att', 'cards_yellow',
       'cards_red', 'xg', 'npxg', 'xg_assist', 'npxg_xg_assist',
       'progressive_carries', 'progressive_passes', 'goals_per90',
       'assists_per90', 'goals_assists_per90', 'goals_pens_per90',
       'goals_assists_pens_per90', 'xg_per90', 'xg_assist_per90',
       'xg_xg_assist_per90', 'npxg_per90', 'npxg_xg_assist_per90'],
      dtype='object')

In [4]:
df['yellow_cards_per_90']=(df['cards_yellow']/df['games']).round(2)
df['red_cards_per_90']=(df['cards_red']/df['games']).round(2)
df['progressive_carries_per_90']=(df['progressive_carries']/df['games']).round(2)
df['progressive_passes_per_90']=(df['progressive_passes']/df['games']).round(2)
df=df.drop(['cards_yellow','cards_red','progressive_carries','progressive_passes','possession','games','minutes','ranker','comp','players_used','avg_age','goals','games_starts','assists','minutes_90s',
       'goals_assists','goals_pens','pens_made','pens_att','xg','npxg','xg_assist','npxg_xg_assist','goals_assists_per90','goals_assists_pens_per90','xg_xg_assist_per90','npxg_xg_assist_per90'],axis=1)

In [5]:
df = df.rename(columns={'goals_pens_per90':'non_pen_goals_per90',})

In [6]:
df

,team,goals_per90,assists_per90,non_pen_goals_per90,xg_per90,xg_assist_per90,npxg_per90,yellow_cards_per_90,red_cards_per_90,progressive_carries_per_90,progressive_passes_per_90
0,Alavés,1.19,0.57,0.95,1.10,0.61,0.88,2.67,0.10,12.29,29.81
1,Angers,1.05,0.68,0.89,1.18,0.82,1.02,1.37,0.05,15.47,29.37
2,Arsenal,1.83,1.39,1.74,1.64,1.23,1.57,2.22,0.17,20.65,45.74
3,Aston Villa,1.43,1.13,1.35,1.47,1.07,1.36,2.17,0.09,17.52,33.43
4,Atalanta,2.14,1.55,2.00,1.67,1.23,1.53,2.05,0.00,22.18,48.41
...,...,...,...,...,...,...,...,...,...,...,...
91,Villarreal,1.76,1.14,1.52,1.77,1.23,1.50,2.86,0.10,17.62,40.67
92,Werder Bremen,1.70,1.30,1.65,1.41,1.08,1.35,2.30,0.20,15.10,40.95
93,West Ham,1.17,0.70,1.04,1.33,0.92,1.23,2.43,0.13,16.78,32.61
94,Wolfsburg,2.16,1.47,2.05,1.52,1.04,1.38,2.63,0.11,12.84,33.11
95,Wolves,1.39,1.17,1.39,1.05,0.87,1.05,2.30,0.09,15.70,31.22

In [7]:
df.isna().sum()

team                          0
goals_per90                   0
assists_per90                 0
non_pen_goals_per90           0
xg_per90                      0
xg_assist_per90               0
npxg_per90                    0
yellow_cards_per_90           0
red_cards_per_90              0
progressive_carries_per_90    0
progressive_passes_per_90     0
dtype: int64

In [8]:
df.to_csv('cleaned_data.csv')